// <auto-generated />
namespace ams.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class inites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inites));
        
        string IMigrationMetadata.Id
        {
            get { return "201602051531098_inites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
